Las elecciones de materiales tienen un inmenso impacto en el rendimiento energético. Esta sección ilustrará cómo Honeybee maneja los materiales modelando ventanas de alto rendimiento.
1.01 Aquí hay una descripción general de todos los módulos que agregaremos a lo largo del capítulo sobre Técnicas Pasivas. Esto se basa directamente en el modelo de zona única que creamos antes. Los elementos originales aparecen en grupos de color gris claro a continuación, y los elementos nuevos aparecen en amarillo.
https://user-images.githubusercontent.com/44324576/52227404-b6a27a00-28af-11e9-8839-6854e4e642e5.png
1.02 Acercándonos, puedes ver que crearemos una construcción para una ventana de alto rendimiento y la conectaremos al componente Honeybee_addHBGlz. Esto reemplazará la suposición predeterminada sobre el acristalamiento con nuestras especificaciones para una ventana de alto rendimiento.
https://user-images.githubusercontent.com/44324576/52228338-6b3d9b00-28b2-11e9-8cea-4fc05f449fbb.png
1.03 Acercándonos aún más, ahora veremos el proceso de creación de una construcción de ventanas de alto rendimiento.
https://user-images.githubusercontent.com/44324576/52228340-6c6ec800-28b2-11e9-9b8c-02ada07437d0.png
1.04 Comience con el componente de construcción Honeybee_EnergyPlus. Una construcción Energy Plus podría ser un solo material en una sola capa (es decir, hormigón sólido) o podría ser un material compuesto (es decir, una estructura de montantes con yeso y aislamiento en el interior). Lo importante es que solo puede tener una construcción por superficie de zona. En este caso, estamos creando una ventana y ya hemos especificado las superficies que pretendemos usar (observe el componente 'House Windows' en la imagen del paso 1.02). 
https://user-images.githubusercontent.com/44324576/52409824-e41d3c80-2ad6-11e9-993a-b7d7f5910c4b.jpg
Nota puedes agregar capas adicionales a una construcción EP haciendo zoom en el componente en Grasshopper hasta que veas los signos más / menos en blanco y negro al lado de los terminales, como en la imagen a continuación:
https://user-images.githubusercontent.com/44324576/52410725-89391480-2ad9-11e9-9e8e-34057df18d72.JPG
1.05 Ahora necesitamos agregar capas de material a esta construcción. Honeybee contiene una variedad de componentes para especificar materiales (ver pestaña 06 | Energía | Materiales) que se pueden añadir como capas a una Construcción EP. La forma más sencilla de modelar una ventana es usar el Material de Ventana de EnergyPlus, que está destinado a describir un conjunto de ventana completo. Esto facilita la conexión de valores de fabricantes que describen una ventana completa en lugar de un material específico.
https://user-images.githubusercontent.com/44324576/52409825-e41d3c80-2ad6-11e9-80c7-7ce489dc8662.jpg
Aquí hay una vista previa del menú de materiales de Honeybee:
https://user-images.githubusercontent.com/44324576/52495175-32623680-2bd0-11e9-95ae-c3eafbb3b9d8.JPG
1.06 Asigne el valor U como 2, el coeficiente de ganancia de calor solar como 0.25 y la transmitancia visible de la ventana como 0.55. El valor U es una medida de aislamiento, el coeficiente de ganancia de calor solar es una medida de cuánta energía solar pasa a través del vidrio, y la transmitancia visible es una medida de cuánta luz visible pasa a través de la ventana.
Nota la distinción entre transmitancia, que es la relación medida de la luz con una incidencia normal, frente a la transmisividad, que es la relación de la luz total que pasa a través del vidrio. No estamos usando Radiance aquí, pero los parámetros de acristalamiento de Radiance requieren transmisividad y los fabricantes de acristalamientos suelen citar la transmitancia.
https://user-images.githubusercontent.com/44324576/52409826-e4b5d300-2ad6-11e9-80fd-553f3f038ad3.jpg
1.07 Ahora podemos conectar esta construcción al componente Honeybee_AddHBGlz para asignar el material a las ventanas que modelamos.
https://user-images.githubusercontent.com/44324576/52228338-6b3d9b00-28b2-11e9-8cea-4fc05f449fbb.png
1.08 Vuelva a ejecutar la simulación haciendo clic en el conmutador de inicio falso y examine el diagrama de equilibrio de energía. Como puede ver a continuación, cuando comparamos el Diagrama de equilibrio de energía de la casa con y sin la ventana de alto rendimiento, reduce significativamente la ganancia de calor solar.
https://user-images.githubusercontent.com/44324576/52350919-e2496f80-2a29-11e9-9614-7e161f37bb3c.gif
